### ISSUE TITLE
如果小键盘的按键对应的码有多个怎么办？

### ISSUE THREAD

**Issue by yanyumihuang** [hansyao/OS-X-ALPS-DRIVER#1]
我的有个数字键是快捷键，按下去相当于同时按了两个键，我不知道咋改。比如你的1是对应ps2[0x48]，但我的1对应的是[0x48][0x48]。这种怎么修改呢？

**Comment by hansyao** [comment]
这个教程里应该写得很清楚了吧。。。。多个按键对应修改代码逻辑的。。。
```c++
bool ApplePS2Keyboard::dispatchKeyboardEventWithPacket(const UInt8* packet)
{

    // handle special cases
    switch (keyCode)
    {

        // ......    

        case 0x45:  //num lock remapping
            keyCode = 0;

            //NUM LOCK fix For DELL Precision M4800
            if(goingDown)
            {
                setNumLockFeedback(_numKeypadLocked);
                _numKeypadLocked = !_numKeypadLocked;
            }

            // remap NUM PAD by NUMLOCK LED status
            if(!_numKeypadLocked)
            {
                _PS2ToADBMap[0x48] = 0x5b;     // 8 up arrow
                _PS2ToADBMap[0x50] = 0x54;     // 2 down arrow
                _PS2ToADBMap[0x4B] = 0x56;     // 4 left arrow
                _PS2ToADBMap[0x4D] = 0x58;     // 6 right arrow
                _PS2ToADBMap[0x52] = 0x52;     // 0 insert / CDROM inject
                _PS2ToADBMap[0x53] = 0x41;     // . delete
                _PS2ToADBMap[0x49] = 0x5c;     // 9 page up
                _PS2ToADBMap[0x51] = 0x55;     // 3 page down
                _PS2ToADBMap[0x47] = 0x59;     // 7 home
                _PS2ToADBMap[0x4F] = 0x53;     // 1 end
                
            }
            else
            {
                _PS2ToADBMap[0x48] = 0x7e;      // 8 up arrow
                _PS2ToADBMap[0x50] = 0x7d;      // 2 down arrow
                _PS2ToADBMap[0x4B] = 0x7b;      // 4 left arrow
                _PS2ToADBMap[0x4D] = 0x7c;      // 6 right arrow
                _PS2ToADBMap[0x52] = 0x92;      // 0 insert / CDROM inject
                _PS2ToADBMap[0x53] = 0x75;      // . delete
                _PS2ToADBMap[0x49] = 0x74;      // 9 page up
                _PS2ToADBMap[0x51] = 0x79;      // 3 page down
                _PS2ToADBMap[0x47] = 0x73;      // 7 home
                _PS2ToADBMap[0x4F] = 0x77;      // 1 end

            }
            break;

        // .......    
    }
}
```

**Comment by yanyumihuang** [comment]
> 这个教程里应该写得很清楚了吧。。。。多个按键对应修改代码逻辑的。。。
> 
> ```c++
> bool ApplePS2Keyboard::dispatchKeyboardEventWithPacket(const UInt8* packet)
> {
> 
>     // handle special cases
>     switch (keyCode)
>     {
> 
>         // ......    
> 
>         case 0x45:  //num lock remapping
>             keyCode = 0;
> 
>             //NUM LOCK fix For DELL Precision M4800
>             if(goingDown)
>             {
>                 setNumLockFeedback(_numKeypadLocked);
>                 _numKeypadLocked = !_numKeypadLocked;
>             }
> 
>             // remap NUM PAD by NUMLOCK LED status
>             if(!_numKeypadLocked)
>             {
>                 _PS2ToADBMap[0x48] = 0x5b;     // 8 up arrow
>                 _PS2ToADBMap[0x50] = 0x54;     // 2 down arrow
>                 _PS2ToADBMap[0x4B] = 0x56;     // 4 left arrow
>                 _PS2ToADBMap[0x4D] = 0x58;     // 6 right arrow
>                 _PS2ToADBMap[0x52] = 0x52;     // 0 insert / CDROM inject
>                 _PS2ToADBMap[0x53] = 0x41;     // . delete
>                 _PS2ToADBMap[0x49] = 0x5c;     // 9 page up
>                 _PS2ToADBMap[0x51] = 0x55;     // 3 page down
>                 _PS2ToADBMap[0x47] = 0x59;     // 7 home
>                 _PS2ToADBMap[0x4F] = 0x53;     // 1 end
>                 
>             }
>             else
>             {
>                 _PS2ToADBMap[0x48] = 0x7e;      // 8 up arrow
>                 _PS2ToADBMap[0x50] = 0x7d;      // 2 down arrow
>                 _PS2ToADBMap[0x4B] = 0x7b;      // 4 left arrow
>                 _PS2ToADBMap[0x4D] = 0x7c;      // 6 right arrow
>                 _PS2ToADBMap[0x52] = 0x92;      // 0 insert / CDROM inject
>                 _PS2ToADBMap[0x53] = 0x75;      // . delete
>                 _PS2ToADBMap[0x49] = 0x74;      // 9 page up
>                 _PS2ToADBMap[0x51] = 0x79;      // 3 page down
>                 _PS2ToADBMap[0x47] = 0x73;      // 7 home
>                 _PS2ToADBMap[0x4F] = 0x77;      // 1 end
> 
>             }
>             break;
> 
>         // .......    
>     }
> }
> ```

你这代码还是一个键对应一个键去进行替换。检测是小写键打开了就将那几个ps码映射到1，2，3，4等等，如果没开就映射到别的。我的问题是我的小数字键盘中有一个键它不是一一对应的。我举一个完整的清晰的例子：
以下数字均为乱写的。
比如按下数字键盘1的时候ps2码是23代表end，也就是说不修复的话按下1就相当于按下end这个键
修复后按下1就是1。
但我的数字键7的ps2码并不是23，而是23 45。也就是说在不修复的情况下按下数字键7相当于按下 end+ctrl键。这个你代码里没说的。我想做的就是将按下end+ctrl这两个键映射为数字7.你写的修复方法都是1个键对一个键的修改。这下我描述的清除了嘛

**Comment by yanyumihuang** [comment]
我自己在

**Comment by yanyumihuang** [comment]
我在vs2的配置文件中经过映射完成了大部分键。当然这种映射就只能执行数字键的功能了。但因为7这个键是两个键的映射，按下它等于按下两个键，所以我没法处理，看到大佬的文章后就来问问咋办？下面是我正确处理的图片，0到9我都做了映射，出了7.我不会弄啊
![image](https://user-images.githubusercontent.com/26965886/136376334-d2213691-22a5-4edc-b01a-499f3d36ec80.png)

**Comment by hansyao** [comment]
> > 这个教程里应该写得很清楚了吧。。。。多个按键对应修改代码逻辑的。。。
> 
> > 
> 
> > ```c++
> 
> > bool ApplePS2Keyboard::dispatchKeyboardEventWithPacket(const UInt8* packet)
> 
> > {
> 
> > 
> 
> >     // handle special cases
> 
> >     switch (keyCode)
> 
> >     {
> 
> > 
> 
> >         // ......    
> 
> > 
> 
> >         case 0x45:  //num lock remapping
> 
> >             keyCode = 0;
> 
> > 
> 
> >             //NUM LOCK fix For DELL Precision M4800
> 
> >             if(goingDown)
> 
> >             {
> 
> >                 setNumLockFeedback(_numKeypadLocked);
> 
> >                 _numKeypadLocked = !_numKeypadLocked;
> 
> >             }
> 
> > 
> 
> >             // remap NUM PAD by NUMLOCK LED status
> 
> >             if(!_numKeypadLocked)
> 
> >             {
> 
> >                 _PS2ToADBMap[0x48] = 0x5b;     // 8 up arrow
> 
> >                 _PS2ToADBMap[0x50] = 0x54;     // 2 down arrow
> 
> >                 _PS2ToADBMap[0x4B] = 0x56;     // 4 left arrow
> 
> >                 _PS2ToADBMap[0x4D] = 0x58;     // 6 right arrow
> 
> >                 _PS2ToADBMap[0x52] = 0x52;     // 0 insert / CDROM inject
> 
> >                 _PS2ToADBMap[0x53] = 0x41;     // . delete
> 
> >                 _PS2ToADBMap[0x49] = 0x5c;     // 9 page up
> 
> >                 _PS2ToADBMap[0x51] = 0x55;     // 3 page down
> 
> >                 _PS2ToADBMap[0x47] = 0x59;     // 7 home
> 
> >                 _PS2ToADBMap[0x4F] = 0x53;     // 1 end
> 
> >                 
> 
> >             }
> 
> >             else
> 
> >             {
> 
> >                 _PS2ToADBMap[0x48] = 0x7e;      // 8 up arrow
> 
> >                 _PS2ToADBMap[0x50] = 0x7d;      // 2 down arrow
> 
> >                 _PS2ToADBMap[0x4B] = 0x7b;      // 4 left arrow
> 
> >                 _PS2ToADBMap[0x4D] = 0x7c;      // 6 right arrow
> 
> >                 _PS2ToADBMap[0x52] = 0x92;      // 0 insert / CDROM inject
> 
> >                 _PS2ToADBMap[0x53] = 0x75;      // . delete
> 
> >                 _PS2ToADBMap[0x49] = 0x74;      // 9 page up
> 
> >                 _PS2ToADBMap[0x51] = 0x79;      // 3 page down
> 
> >                 _PS2ToADBMap[0x47] = 0x73;      // 7 home
> 
> >                 _PS2ToADBMap[0x4F] = 0x77;      // 1 end
> 
> > 
> 
> >             }
> 
> >             break;
> 
> > 
> 
> >         // .......    
> 
> >     }
> 
> > }
> 
> > ```
> 
> 
> 
> 你这代码还是一个键对应一个键去进行替换。检测是小写键打开了就将那几个ps码映射到1，2，3，4等等，如果没开就映射到别的。我的问题是我的小数字键盘中有一个键它不是一一对应的。我举一个完整的清晰的例子：
> 
> 以下数字均为乱写的。
> 
> 比如按下数字键盘1的时候ps2码是23代表end，也就是说不修复的话按下1就相当于按下end这个键
> 
> 修复后按下1就是1。
> 
> 但我的数字键7的ps2码并不是23，而是23 45。也就是说在不修复的情况下按下数字键7相当于按下 end+ctrl键。这个你代码里没说的。我想做的就是将按下end+ctrl这两个键映射为数字7.你写的修复方法都是1个键对一个键的修改。这下我描述的清除了嘛

PS码有一个按键只会对应一个不会有多个的，但是一个ps码可以对应多个adb码，这就是你按键得到多个ADB码的原因，因此需要按照这个逻辑修复。

**Comment by hansyao** [comment]
如测试按键被映射到了多个ADB码，你得分析下代码其他什么地方将ADB码错误地映射到了这个键上，然后修改代码移除之……具体情况需要具体分析，有可能是驱动代码中的问题，也可能是dsdt的acpi规范问题

**Comment by hansyao** [comment]
另外如果出现组合键的ps码修改逻辑差不多的，你可以参见ctr+alt+del键的修复例子

**Comment by yanyumihuang** [comment]
> PS码有一个按键只会对应一个不会有多个的，但是一个ps码可以对应多个adb码，这就是你按键得到多个ADB码的原因，因此需要按照这个逻辑修复。

我这个好像跟你说的不一样，是三个ps2对应到三个adb。
这是我按下数字7的截图都是没有对kex修改的情况下
![image](https://user-images.githubusercontent.com/26965886/136381080-3aa42e28-5075-464e-8067-f041b4d8bc4a.png)

这是我按下数字1的截图。
![image](https://user-images.githubusercontent.com/26965886/136380899-4a2e030d-6677-4dbb-aa24-fc6240d0f961.png)
ke可以看出来按下7的时候前后都不一样
按下1的时候就只有后面的不一样

**Comment by hansyao** [comment]
左边是PS码，右边是ADB码，如果按下7出现3个PS码说明触发了组合键逻辑，你按照组合键的逻辑修复即可，参见ctl+alt+del键的修复例子，将7键看成是这3个ps码的组合键即可

**Comment by yanyumihuang** [comment]
> 左边是PS码，右边是ADB码，如果按下7出现3个PS码说明触发了组合键逻辑，你按照组合键的逻辑修复即可，参见ctl+alt+del键的修复例子，将7键看成是这3个ps码的组合键即可
我知道我咋改了，先看看这几个键有没有奇特之处，然后进行修改，在按下7键相当于按下a1,a2,a3，此时先判断a1，a2是否被按下，如果被按下就判断a3是否被按下，如果是话就一行这个dispatchKeyboardEventX(7对应的ps2码, true, now_abs);这样的逻辑对吧？
你是将ctl+alt+del映射到ctl+alt+Q，然后呢？你按下ctl+alt+del相当于按下ctl+alt+Q，然后是去设置里的快捷键里改吗？

**Comment by hansyao** [comment]
ctl+alt+Q是苹果系统的默认的锁屏快捷键所以直接映射给它即可。Ctl+Alt+Del由于要做防呆误触所以监测按键逻辑复杂点需要一个一个判断，你这个按键的逻辑应该简单点只需要判断一次是不是三个按键全都按下了即可，一行代码即可搞定。具体还是得看你测试的结果

**Comment by yanyumihuang** [comment]
> ctl+alt+Q是苹果系统的默认的锁屏快捷键所以直接映射给它即可。Ctl+Alt+Del由于要做防呆误触所以监测按键逻辑复杂点需要一个一个判断，你这个按键的逻辑应该简单点只需要判断一次是不是三个按键全都按下了即可，一行代码即可搞定。具体还是得看你测试的结果

确实。我已经在下载Xcode了。我去试试，如果有问题还是要请教你。麻烦了

**Comment by yanyumihuang** [comment]
我已经放弃了。Xcode的环境有问题，总是提示缺少文件，不管是你提供的GitHub仓库，还是acidanthera这个人的仓库，总是提示缺少iOService.h文件，google一波，pcbeta爬楼都没有找到办法。看来应该是Xcode的设置了，或者我少下什么东西了。

**Comment by hansyao** [comment]
你自己不会搭建本地运行环境的话，可以直接用github actions编译，fork acidanthera的项目，在github上修改好你的代码，运行一下actions就可以了，编译好的文件会在你的release assets里下载下来就好了，这个acidanthera的workflow CI把环境都搭建好了。不过调试环境不建议，因为可能会有很多bug编译不通过的话每次都跑action有点麻烦。或者你研究以下他的workflow源码，按部就班在本地把依赖环境搭建好了即可，这个很简单的，就是缺少依赖，把依赖问题解决了就好了

**Comment by hansyao** [comment]
不过你用的acidanthera的仓库的话，你基于他的源码改即可，注意下最好不要全部照抄我的源码，因为我的依赖环境和他的是不一样的。

**Comment by yanyumihuang** [comment]
> 不过你用的acidanthera的仓库的话，你基于他的源码改即可，注意下最好不要全部照抄我的源码，因为我的依赖环境和他的是不一样的。
感谢指导，又经过三个小时的不断排错，现在终于可以了。我对c++不熟，你定义的变量numKeypadLocked，在进行编译时会报use of undeclared identifier '_numKeypadLocked'，我也不知道为啥。改了很多次也不行。最后就干脆把判断数字锁定键的功能给关了。小键盘就永远当你的数字输入器，也就是功能键全费。这样我已经很满意了，功能键我都很少使用。 
1234567890.如果方便的话发一下付款码，请您喝杯可乐。

**Comment by hansyao** [comment]
这个变量问题应该是你没有声明的缘故，需要在函数头部加一行代码先声明一下类型才可以，付款码如下，🙏![image](https://user-images.githubusercontent.com/6515810/136513220-c70a5e69-2722-45fb-a72c-6f0e0b82a601.jpeg)

**Comment by hansyao** [comment]
我这个函数声明在201行，这个比较基础教程里没写。[_numKeypadLocked](../blob/bfb24b2fc057b5f914e9e8ef3ae318e9077a8798/VoodooPS2Keyboard/VoodooPS2Keyboard.cpp#L201)

**Comment by yanyumihuang** [comment]
> 我这个函数声明在201行，这个比较基础教程里没写。[_numKeypadLocked](../blob/bfb24b2fc057b5f914e9e8ef3ae318e9077a8798/VoodooPS2Keyboard/VoodooPS2Keyboard.cpp#L201)

我只看了你的教程，没看你的代码。我查了这个错误，知道是没声明。但忘记全局变量要在函数外声明了，后来就把这个变量当成一个系统变量。然后我就开始傻逼了。不管咋说，谢谢帮忙。那我就把这个issue关掉了
